#Shimeji-ee Configuration Options
#Thu Jan 15 17:05:43 PST 2026
Filter=nearest
Opacity=1.0
Breeding=true
Sounds=true
Transformation=true
MenuDPI=120
Transients=true
Throwing=true
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger/a/e/i/o/u/discord
AlwaysShowShimejiChooser=false
Scaling=1.0
Environment=generic
ActiveShimeji=Steve
AlwaysShowInformationScreen=false
InteractiveWindowsBlacklist=
