#Shimeji-ee Configuration Options
#Thu Aug 24 21:04:14 CEST 2023
MenuDPI=96
InteractiveWindows=a/i/u/e/o
InteractiveWindowsBlacklist=BongoCat
ShimejiEENameOverride=Kazeem
Scaling=1
ActiveShimeji=Kazeem
AlwaysShowShimejiChooser=false
